### ISSUE TITLE
Exception thrown by clicking on any button in the main menu

### ISSUE THREAD

**Issue by Phariax** [raylib-extras/RPGExample#2]
Clicking on any button in the main menu throws an exception from raudio.c file. 

OS: Win10
IDE: VS2022
Solution Config: Debug/x64 

Repro: 
1. Start the RPGExample project from visual studio.
2. In the main menu, click on any button.
3. Exception has been thrown.

**Comment by JeffM2501** [comment]
Ok, this has to do with the working directory when the game is run. It can't find the audio files and crashes.

I've updated the example to the current raylib and added code that sets the working directory correctly. It should work much better now.

Thank you for the report.
