### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by cosinekitty** [raylib-extras/RPGExample#4]
https://github.com/raylib-extras/RPGExample/blob/c372af0a2ac0390019e57c7efedcc8b4b905c77c/RPG/loading.cpp#L208

When `id` has the same value as `LoadedTextures.size()`, this condition evaluates to false, causing the line `return LoadedTextures[id];` to be executed. This accesses beyond the end of the vector, which is undefined behavior. The `>` should be `>=`.

**Comment by JeffM2501** [comment]
Thanks for catching that, it's been fixed.
